### ISSUE TITLE
IPNetwork("Prefix") returns errors in python 3.5

### ISSUE THREAD

**Issue by diman512** [netaddr/netaddr#195] opened 2020-02-08 14:14 UTC
IPNetwork('192.168.0.0/16').info  returns an error in python 3.5 (which is going to be in Saltstack for a while) but not in  2.7 or 3.7.

 >>> ip = IPNetwork('192.168.0.0/16')
>>> ip
IPNetwork('192.168.0.0/16')
>>> ip.info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/__init__.py", line 222, in info
    from netaddr.ip.iana import query
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/iana.py", line 443, in <module>
    load_info()
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/iana.py", line 381, in load_info
    mcast.parse()
  File "/usr/local/lib/python3.6/dist-packages/netaddr/ip/iana.py", line 143, in parse
    self.xmlparser.parse(self.fh)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 123, in parse
    buffer = file.read(self._bufsize)
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45141: ordinal not in range(128)
>>>

**Comment by jstasiak** [comment] 2020-06-15 16:52
I can't reproduce this on any Python version (test commit https://github.com/netaddr/netaddr/commit/bc38c55f3aee550692385f8aa227bb36f70a0d01 resulting in a bunch of CI jobs: https://github.com/netaddr/netaddr/actions/runs/136222419).

What Python version and netaddr versions are we talking about exactly? You mention 3.5 but there's 3.6 in your stack trace.

**Comment by jstasiak** [comment] 2020-06-15 17:02
Well, I actually can reproduce it if I set the locale to `C` or `POSIX`. Python 3.7+ works fine for you because of [PEP 538](https://www.python.org/dev/peps/pep-0538/) which makes UTF-8 the default encoding when the `C` locale is used. I don't think there's an easy way to change the way `xml.sax` tries to decode the data we give it so as a workaround I'd recommend setting the locale to a UTF-8-based one.

**Comment by jstasiak** [comment] 2020-06-20 23:04
I think the explanation and workaround mentioned above should be appropriate so I'll close this issue. Please feel free to reopen if this causes issues despite a UTF-8 locale being set.

**Closed by jstasiak** 2020-06-20 23:04 UTC
