### ISSUE TITLE
[warning] Python3 SyntaxWarning

### ISSUE THREAD

**Issue by ionutnechita** [netaddr/netaddr#216] opened 2020-09-16 07:58 UTC
/usr/lib/python3/dist-packages/netaddr/strategy/__init__.py:189: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if word_sep is not '':

python3-netaddr (0.7.19-3)
Ubuntu 20.04.1

**Comment by jstasiak** [comment] 2020-09-16 08:00
Thanks for the reports, this is a duplicate of other issues (https://github.com/netaddr/netaddr/search?q=syntaxwarning&type=issues) and is already fixed in 0.8.0.

**Closed by jstasiak** 2020-09-16 08:00 UTC

**Comment by ionutnechita** [comment] 2020-09-16 08:20
Thanks.
